### ISSUE TITLE
Remove console.log

### ISSUE THREAD

**Issue by wstrm** [tcrowe/cjdns-admin#1]
Hi,

Is it possible to remove the `console.log` in response.js?
Would be nice to handle the error myself.

**Comment by tcrowe** [comment]
I'm sorry I didn't see this sooner. I'll look for any more instances of `console.log` and post back here.

I've got 0.2.0 rolling out tonight.

**Comment by tcrowe** [comment]
0.2.0 rolled out. No `console.log` are in the library section of the app. No output will pollute your app.
